name: packages
description: "A new Flutter project."
publish_to: 'none' # Private project, do not publish

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  country_picker: ^2.0.27
  flutter_staggered_grid_view: ^0.7.0
  curved_labeled_navigation_bar: ^2.0.6
  convex_bottom_bar: ^3.2.0
  convex_bottom_bar_renew: ^1.0.2
  video_player: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/videos/
